"""source_add_last_task_processed_at

Revision ID: 01dd81b38e7e
Revises: a6f3659056dd
Create Date: 2026-09-28 00:59:20.681309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dd81b38e7e'
down_revision: Union[str, Sequence[str], None] = 'a6f3659056dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_task_processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_task_processed_at')
    # ### end Alembic commands ###
