"""page_add_raw_size

Revision ID: 4e9c772c6d73
Revises: bee45c4c89f2
Create Date: 2026-09-30 22:35:27.587699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9c772c6d73'
down_revision: Union[str, Sequence[str], None] = 'bee45c4c89f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('content_size_in_kbytes', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('raw_size_in_kbytes', sa.Integer(), nullable=True))
    op.drop_column('pages', 'size_in_kbytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('size_in_kbytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pages', 'raw_size_in_kbytes')
    op.drop_column('pages', 'content_size_in_kbytes')
    # ### end Alembic commands ###
