"""source_change_name_to_last_task_created_at

Revision ID: 55921907a75e
Revises: 71a4990f4ad1
Create Date: 2026-09-27 01:01:48.542265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55921907a75e'
down_revision: Union[str, Sequence[str], None] = '71a4990f4ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_task_created_at', sa.DateTime(), nullable=True))
    op.drop_column('sources', 'last_fetched_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('sources', 'last_task_created_at')
    # ### end Alembic commands ###
