"""initial migration

Revision ID: 71a4990f4ad1
Revises: 
Create Date: 2026-09-26 14:58:21.998940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a4990f4ad1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_task_created_at', sa.DateTime(), nullable=True),
    sa.Column('sitemap_url', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('refetch_seconds', sa.Integer(), nullable=False),
    sa.Column('global_sitemap_url', sa.String(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_processing_tasks',
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='processingtaskstatus'), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitemap_processing_tasks',
    sa.Column('sitemap_url', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('GLOBAL', 'LOCAL', name='sitemaptype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='processingtaskstatus'), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitemap_processing_tasks')
    op.drop_table('page_processing_tasks')
    op.drop_table('sources')
    op.drop_table('pages')
    # ### end Alembic commands ###
