"""source_add_max_pages_count

Revision ID: 8cd9c093e238
Revises: c11028ba0963
Create Date: 2026-09-28 09:58:47.532552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd9c093e238'
down_revision: Union[str, Sequence[str], None] = 'c11028ba0963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('max_pages_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'max_pages_count')
    # ### end Alembic commands ###
