"""source_add_page_count_field

Revision ID: a0b1d75a0856
Revises: 8cd9c093e238
Create Date: 2026-09-28 10:08:04.721197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b1d75a0856'
down_revision: Union[str, Sequence[str], None] = '8cd9c093e238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('page_count', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'page_count')
    # ### end Alembic commands ###
