"""page_add_processing_time

Revision ID: a6f3659056dd
Revises: d784c20f57c1
Create Date: 2026-09-27 17:03:00.531188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6f3659056dd'
down_revision: Union[str, Sequence[str], None] = 'd784c20f57c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('last_task_processed_at', sa.DateTime(), nullable=True))
    op.drop_column('pages', 'last_task_created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('last_task_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pages', 'last_task_processed_at')
    # ### end Alembic commands ###
