"""page_add_page_size

Revision ID: bee45c4c89f2
Revises: 62c0d813ff81
Create Date: 2026-09-30 22:34:39.438333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee45c4c89f2'
down_revision: Union[str, Sequence[str], None] = '62c0d813ff81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('size_in_kbytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'size_in_kbytes')
    # ### end Alembic commands ###
