"""page_add_source_relation

Revision ID: d784c20f57c1
Revises: 55921907a75e
Create Date: 2026-09-27 15:14:49.794950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd784c20f57c1'
down_revision: Union[str, Sequence[str], None] = '55921907a75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('source_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'pages', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_column('pages', 'source_id')
    # ### end Alembic commands ###
